//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 12:03:26 AM EEST 
//


package com.kraptis91;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kraptis91 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Field_QNAME = new QName("http://kraptis91.com", "field");
    private final static QName _Author_QNAME = new QName("http://kraptis91.com", "author");
    private final static QName _Note_QNAME = new QName("http://kraptis91.com", "note");
    private final static QName _Url_QNAME = new QName("http://kraptis91.com", "url");
    private final static QName _Cite_QNAME = new QName("http://kraptis91.com", "cite");
    private final static QName _Crossref_QNAME = new QName("http://kraptis91.com", "crossref");
    private final static QName _Editor_QNAME = new QName("http://kraptis91.com", "editor");
    private final static QName _Address_QNAME = new QName("http://kraptis91.com", "address");
    private final static QName _Title_QNAME = new QName("http://kraptis91.com", "title");
    private final static QName _Booktitle_QNAME = new QName("http://kraptis91.com", "booktitle");
    private final static QName _Pages_QNAME = new QName("http://kraptis91.com", "pages");
    private final static QName _Year_QNAME = new QName("http://kraptis91.com", "year");
    private final static QName _Journal_QNAME = new QName("http://kraptis91.com", "journal");
    private final static QName _Volume_QNAME = new QName("http://kraptis91.com", "volume");
    private final static QName _Number_QNAME = new QName("http://kraptis91.com", "number");
    private final static QName _Month_QNAME = new QName("http://kraptis91.com", "month");
    private final static QName _Ee_QNAME = new QName("http://kraptis91.com", "ee");
    private final static QName _School_QNAME = new QName("http://kraptis91.com", "school");
    private final static QName _Publisher_QNAME = new QName("http://kraptis91.com", "publisher");
    private final static QName _Cdrom_QNAME = new QName("http://kraptis91.com", "cdrom");
    private final static QName _Isbn_QNAME = new QName("http://kraptis91.com", "isbn");
    private final static QName _Chapter_QNAME = new QName("http://kraptis91.com", "chapter");
    private final static QName _Series_QNAME = new QName("http://kraptis91.com", "series");
    private final static QName _Publnr_QNAME = new QName("http://kraptis91.com", "publnr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kraptis91
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dblp }
     * 
     */
    public Dblp createDblp() {
        return new Dblp();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Inproceedings }
     * 
     */
    public Inproceedings createInproceedings() {
        return new Inproceedings();
    }

    /**
     * Create an instance of {@link Proceedings }
     * 
     */
    public Proceedings createProceedings() {
        return new Proceedings();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link Incollection }
     * 
     */
    public Incollection createIncollection() {
        return new Incollection();
    }

    /**
     * Create an instance of {@link Phdthesis }
     * 
     */
    public Phdthesis createPhdthesis() {
        return new Phdthesis();
    }

    /**
     * Create an instance of {@link Mastersthesis }
     * 
     */
    public Mastersthesis createMastersthesis() {
        return new Mastersthesis();
    }

    /**
     * Create an instance of {@link Www }
     * 
     */
    public Www createWww() {
        return new Www();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link Cite }
     * 
     */
    public Cite createCite() {
        return new Cite();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Editor }
     * 
     */
    public Editor createEditor() {
        return new Editor();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Booktitle }
     * 
     */
    public Booktitle createBooktitle() {
        return new Booktitle();
    }

    /**
     * Create an instance of {@link Pages }
     * 
     */
    public Pages createPages() {
        return new Pages();
    }

    /**
     * Create an instance of {@link Year }
     * 
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link Journal }
     * 
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link Volume }
     * 
     */
    public Volume createVolume() {
        return new Volume();
    }

    /**
     * Create an instance of {@link Number }
     * 
     */
    public Number createNumber() {
        return new Number();
    }

    /**
     * Create an instance of {@link Month }
     * 
     */
    public Month createMonth() {
        return new Month();
    }

    /**
     * Create an instance of {@link Ee }
     * 
     */
    public Ee createEe() {
        return new Ee();
    }

    /**
     * Create an instance of {@link School }
     * 
     */
    public School createSchool() {
        return new School();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link Isbn }
     * 
     */
    public Isbn createIsbn() {
        return new Isbn();
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link Publnr }
     * 
     */
    public Publnr createPublnr() {
        return new Publnr();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link I }
     * 
     */
    public I createI() {
        return new I();
    }

    /**
     * Create an instance of {@link Tt }
     * 
     */
    public Tt createTt() {
        return new Tt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "field")
    public JAXBElement<Object> createField(Object value) {
        return new JAXBElement<Object>(_Field_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Author }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "author", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Author> createAuthor(Author value) {
        return new JAXBElement<Author>(_Author_QNAME, Author.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Note }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "note", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Note> createNote(Note value) {
        return new JAXBElement<Note>(_Note_QNAME, Note.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Url }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "url", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Url> createUrl(Url value) {
        return new JAXBElement<Url>(_Url_QNAME, Url.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cite }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "cite", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Cite> createCite(Cite value) {
        return new JAXBElement<Cite>(_Cite_QNAME, Cite.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "crossref", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<String> createCrossref(String value) {
        return new JAXBElement<String>(_Crossref_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Editor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "editor", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Editor> createEditor(Editor value) {
        return new JAXBElement<Editor>(_Editor_QNAME, Editor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "address", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Address> createAddress(Address value) {
        return new JAXBElement<Address>(_Address_QNAME, Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Title }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "title", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Title> createTitle(Title value) {
        return new JAXBElement<Title>(_Title_QNAME, Title.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Booktitle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "booktitle", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Booktitle> createBooktitle(Booktitle value) {
        return new JAXBElement<Booktitle>(_Booktitle_QNAME, Booktitle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pages }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "pages", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Pages> createPages(Pages value) {
        return new JAXBElement<Pages>(_Pages_QNAME, Pages.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Year }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "year", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Year> createYear(Year value) {
        return new JAXBElement<Year>(_Year_QNAME, Year.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Journal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "journal", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Journal> createJournal(Journal value) {
        return new JAXBElement<Journal>(_Journal_QNAME, Journal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Volume }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "volume", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Volume> createVolume(Volume value) {
        return new JAXBElement<Volume>(_Volume_QNAME, Volume.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Number }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "number", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Number> createNumber(Number value) {
        return new JAXBElement<Number>(_Number_QNAME, Number.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Month }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "month", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Month> createMonth(Month value) {
        return new JAXBElement<Month>(_Month_QNAME, Month.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ee }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "ee", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Ee> createEe(Ee value) {
        return new JAXBElement<Ee>(_Ee_QNAME, Ee.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link School }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "school", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<School> createSchool(School value) {
        return new JAXBElement<School>(_School_QNAME, School.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Publisher }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "publisher", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Publisher> createPublisher(Publisher value) {
        return new JAXBElement<Publisher>(_Publisher_QNAME, Publisher.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "cdrom", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<String> createCdrom(String value) {
        return new JAXBElement<String>(_Cdrom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Isbn }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "isbn", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Isbn> createIsbn(Isbn value) {
        return new JAXBElement<Isbn>(_Isbn_QNAME, Isbn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "chapter", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<String> createChapter(String value) {
        return new JAXBElement<String>(_Chapter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Series }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "series", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Series> createSeries(Series value) {
        return new JAXBElement<Series>(_Series_QNAME, Series.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Publnr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kraptis91.com", name = "publnr", substitutionHeadNamespace = "http://kraptis91.com", substitutionHeadName = "field")
    public JAXBElement<Publnr> createPublnr(Publnr value) {
        return new JAXBElement<Publnr>(_Publnr_QNAME, Publnr.class, null, value);
    }

}
