//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 12:01:45 AM EEST 
//


package com.kraptis91;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{http://kraptis91.com}article"/&gt;
 *         &lt;element ref="{http://kraptis91.com}inproceedings"/&gt;
 *         &lt;element ref="{http://kraptis91.com}proceedings"/&gt;
 *         &lt;element ref="{http://kraptis91.com}book"/&gt;
 *         &lt;element ref="{http://kraptis91.com}incollection"/&gt;
 *         &lt;element ref="{http://kraptis91.com}phdthesis"/&gt;
 *         &lt;element ref="{http://kraptis91.com}mastersthesis"/&gt;
 *         &lt;element ref="{http://kraptis91.com}www"/&gt;
 *         &lt;element ref="{http://kraptis91.com}person"/&gt;
 *         &lt;element ref="{http://kraptis91.com}data"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="mdate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleOrInproceedingsOrProceedings"
})
@XmlRootElement(name = "dblp")
public class Dblp {

    @XmlElements({
        @XmlElement(name = "article", type = Article.class),
        @XmlElement(name = "inproceedings", type = Inproceedings.class),
        @XmlElement(name = "proceedings", type = Proceedings.class),
        @XmlElement(name = "book", type = Book.class),
        @XmlElement(name = "incollection", type = Incollection.class),
        @XmlElement(name = "phdthesis", type = Phdthesis.class),
        @XmlElement(name = "mastersthesis", type = Mastersthesis.class),
        @XmlElement(name = "www", type = Www.class),
        @XmlElement(name = "person", type = Person.class),
        @XmlElement(name = "data", type = Data.class)
    })
    protected List<Object> articleOrInproceedingsOrProceedings;
    @XmlAttribute(name = "mdate")
    @XmlSchemaType(name = "anySimpleType")
    protected String mdate;

    /**
     * Gets the value of the articleOrInproceedingsOrProceedings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articleOrInproceedingsOrProceedings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticleOrInproceedingsOrProceedings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Article }
     * {@link Inproceedings }
     * {@link Proceedings }
     * {@link Book }
     * {@link Incollection }
     * {@link Phdthesis }
     * {@link Mastersthesis }
     * {@link Www }
     * {@link Person }
     * {@link Data }
     * 
     * 
     */
    public List<Object> getArticleOrInproceedingsOrProceedings() {
        if (articleOrInproceedingsOrProceedings == null) {
            articleOrInproceedingsOrProceedings = new ArrayList<Object>();
        }
        return this.articleOrInproceedingsOrProceedings;
    }

    /**
     * Gets the value of the mdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdate() {
        return mdate;
    }

    /**
     * Sets the value of the mdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdate(String value) {
        this.mdate = value;
    }

}
